version: '3'
services:
  tornado:
    build: .
    container_name: tornado
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/build
      - /app/.env
      - /app/index.js
