name: Integration Test

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  integration:
    name: 'Run Integration Tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Integration Test
      run: sh scripts/test.sh
